version: "3.9"
services:
  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    ports:
      - '3000:3000'
  admin:
    build: ./admin
    container_name: admin-client
    restart: unless-stopped
    ports:
      - '4000:80'
  client:
    build: ./client
    container_name: client
    restart: unless-stopped
    ports:
      - '5000:80'